### ISSUE TITLE
Fetch runmode at run time using an env variable

### ISSUE THREAD

**Issue by dev-ritik** [mdg-iitr/Codephile#192]

**Comment by Saksham-Sharma-99** [comment]
I need a little guidance on how to do it . please help

**Comment by dev-ritik** [comment]
This issue aimed to hide the docs in production but keep it available for our debug environment. This has already been handled. The issue is that `runmode` is hardcoded as of now here: https://github.com/mdg-iitr/Codephile/blob/176cc50a1ce13af9f74c82004effe2f8b1fcd34c/conf/app.conf#L3
We need to fetch this mode dynamically at run time.

**Comment by Saksham-Sharma-99** [comment]
I'm assuming we are deploying the backend on heroku or aws .. so port used there must be different than 8080 in the .env file.
Based on this , can we set the runmode accordingly.

<img width="529" alt="Screenshot 2021-03-27 at 1 13 30 PM" src="https://user-images.githubusercontent.com/63503364/112714021-4bd4b280-8efe-11eb-86ec-a62bb86d5d0a.png">
